---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./coredns.yaml
  - ./jetstack.yaml
  - ./metrics-server.yaml
  - ./openebs.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./spegel.yaml
  - ./stakater.yaml
  - ./external-dns.yaml
  - ./ingress-nginx.yaml
  - ./k8s-gateway.yaml
  - ./k8s-at-home.yaml
#  - ./kiali.yaml
  - ./nfs-subdir-external.yaml
  - ./grafana.yaml
#  - ./uptrace.yaml
  - ./onechart.yaml
#  - ./authentik.yaml
  - ./robusta.yaml
  - ./csi-driver-nfs.yaml
  - ./kubeflame.yaml
  - ./checkmk.yaml
  - ./budibase.yaml
