apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:hUxnbS6hLa7bWLE=,iv:jyPDcqUojFeLJNPPLt22MqJd38fxMCeaPQ2KRQeX+Sk=,tag:sVbq/uvZfbUN6wQRnd+5xg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:+jgICDZJU5pa7wj7wSVS3D42MeTTHQ==,iv:Zw8uFGPN4BQc3xs7fe0OA5rEAuZ8PfpWLUK1kpfMLiQ=,tag:flhOYf4ddVr2XiU4aH/lvA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:RdAZ42zqPWVRn7gJLZEq68LnjDENKoU0s/t1C2VL7s89Tl1g,iv:NeDwKPx9I0ibXBuUaJSiSDHH3KSyJMUmLkRht0XKSAU=,tag:5DRWG7dQC22VizvToPS/Yg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m3cj7a2auwuanpqtugv29834mmlwqzcd43tjnczqwts3k9tgv35q86xkl7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuV3Z3ZURvWjluQXlzZ1RD
            dFhySFZaL2VqczlDUDdaemhpTWJsS3FxWjAwCnMyMlJHOHBDbVFEeGJiL29xR2RG
            Z01iQ3RrTUhhTTVCNWFZUDlWdVV1Y3cKLS0tIHNOZWlFZSt3R2N2SXQ1T1lyaEtv
            YjRnMFpBUFdVTHVaQ1A3TVZ0eDlYV2MKp7VuREZ3L/vNA8XWKtrEmJMJMQm2+Jv9
            lPEgiwPe3zJvogLVpKy1+AkfRfkrP/hf6HLzh/j4f4DjYh1hTs147A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-08T16:24:13Z"
    mac: ENC[AES256_GCM,data:jOBpKI9rWkcKsvQWj+X5t+qt8CoQ/uytwo83v0j4ucMZ/BIUylwkWHZPp0tLDRwWgMyTnSgmL1ID1DzPmL0Zs8X6NvpSfdaQga7lwWlXXC+qZW5PuR25SUY3iHv4fzsC3Ic6jssmoXjEyGMYzT1TyyVHsgTgCS2R1dUouNGCopM=,iv:EdPipvA59ccDNGK1vgbWIwRiolI4K/cvTOsIWeqQZBo=,tag:lxLgHSW6lphyL3+YhSFAWg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
